name: CI for Relaying-Services-SDK

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'

            - name: Install dependencies
              run: npm install

            - name: Check Linter bugs
              run: npm run lint

            - name: Check Codestyles errors
              run: npm run prettier

            - name: Run tests
              run: npm run test